blank_issues_enabled: false
contact_links:
  - name: GDG on Campus SRM Technical Support
    url: mailto:technical@gdgsrm.com
    about: For questions regarding the recruitment tasks and technical submissions.
